name: Pipeline

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      # =========================
      # Backend
      # =========================
      - name: Install Backend Dependencies
        working-directory: backend
        run: npm ci

      - name: Build Backend
        working-directory: backend
        run: npm run build

      # =========================
      # Frontend
      # =========================
      - name: Install Frontend Dependencies
        working-directory: frontend/bddTrainTwo
        run: npm ci

      - name: Build Frontend
        working-directory: frontend/bddTrainTwo
        run: npm run build

      # =========================
      # BDD
      # =========================
      - name: Install BDD Dependencies
        working-directory: BDD
        run: npm ci

      - name: Install Playwright Browsers
        working-directory: BDD
        run: npx playwright install --with-deps

      - name: Run BDD Tests
        working-directory: BDD
        run: npm run test:bdd

      # =========================
      # Final
      # =========================
      - name: List Files
        run: ls -la

      - name: Pipeline Completed
        run: echo "✅ Pipeline completed successfully!"
